routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/','HomeController@index');

Route::get('dashboard/login', 'Dashboard\AuthController@login')->name('login');
Route::post('dashboard/login', 'Dashboard\AuthController@authenticate');
Route::post('dashboard/logout', 'Dashboard\AuthController@logout')->name('logout');

Route::get('/student/login', 'Dashboard\AuthController@login_student')->name('login_student');
Route::post('/student/login', 'Dashboard\AuthController@authenticate_student');
Route::post('/student/logout', 'Dashboard\AuthController@logout_student')->name('logout_student');

Route::group(['middleware'=>'auth:web'],function () {
    Route::get('/student', 'Dashboard\StudentController@index')->name('student');
    Route::get('/student/subjects/video', 'Dashboard\StudentController@video')->name('video_student');
    Route::post('student/subjects/video/add','Dashboard\StudentController@video_add')->name('add_video_student');

    Route::get('/student/subjects/sheet', 'Dashboard\StudentController@sheet')->name('sheet_student');
    Route::post('student/subjects/sheet/add','Dashboard\StudentController@sheet_add')->name('add_sheet_student');

    Route::get('/student/subjects/summary', 'Dashboard\StudentController@summary')->name('summary_student');
    Route::post('student/subjects/summary/add','Dashboard\StudentController@summary_add')->name('add_summary_student');

    Route::get('student/getSubject', 'Dashboard\StudentController@get_subject')->name('get_subject_student');


});
Route::group(['middleware'=>'auth:admin'],function () {
    Route::get('dashboard', 'Dashboard\DashboardController@index')->name('dashboard');

    Route::get('dashboard/user/all','Dashboard\UserController@all')->name('users');
    Route::get('dashboard/user/normal','Dashboard\UserController@normal')->name('user_normal');
    Route::get('dashboard/user/excellent','Dashboard\UserController@excellent')->name('user_excellent');
    Route::get('dashboard/user/balance','Dashboard\UserController@balance')->name('user_balance');

    Route::get('dashboard/user/normal/{id}','Dashboard\UserController@to_normal')->name('to_normal');
    Route::get('dashboard/user/excellent/{id}','Dashboard\UserController@to_excellent')->name('to_excellent');
    Route::post('dashboard/user/level/add/','Dashboard\UserController@add_level')->name('add_level_user');
    Route::get('dashboard/user/level/del/{id}','Dashboard\UserController@del_level')->name('del_level_user');
    Route::post('dashboard/user/department/change/','Dashboard\UserController@change_department')->name('change_department');
    Route::get('dashboard/user/del/{id}','Dashboard\UserController@del_user')->name('del_user');
    Route::post('dashboard/user/data','Dashboard\UserController@user_data')->name('user_data');

    Route::get('dashboard/user/payment','Dashboard\UserController@Request_Payment')->name('request_payment');
    Route::post('dashboard/user/payment/approve','Dashboard\UserController@Approve_Request')->name('approve_request');
    Route::get('dashboard/user/payment/del/{id}','Dashboard\UserController@del_Request')->name('del_request');

    Route::post('dashboard/user/verified','Dashboard\UserController@verified')->name('verified');
    Route::post('dashboard/user/rank','Dashboard\UserController@rank')->name('rank');
    Route::get('dashboard/user/deadline','Dashboard\UserController@deadline')->name('check_deadline');
    Route::post('dashboard/user/status','Dashboard\UserController@status')->name('update_status');
    Route::get('dashboard/user/statics','Dashboard\UserController@statics')->name('user_statics');
    Route::post('dashboard/user/reset','Dashboard\UserController@reset')->name('user_reset');
    Route::post('dashboard/user/promo','Dashboard\UserController@promo')->name('user_promo');
    Route::get('dashboard/getUser', 'Dashboard\UserController@get_user')->name('get_user');

    Route::post('dashboard/university/add','Dashboard\UniversityController@add')->name('add_university');
    Route::post('dashboard/university/edit/{id}','Dashboard\UniversityController@edit')->name('edit_university');
    Route::get('dashboard/university/del/{id}','Dashboard\UniversityController@delete')->name('del_university');

    Route::get('dashboard/getFaculty', 'Dashboard\FacultyController@get_faculty')->name('get_faculty');
    Route::get('dashboard/faculty','Dashboard\FacultyController@index')->name('faculty');
    Route::post('dashboard/faculty/add','Dashboard\FacultyController@add')->name('add_faculty');
    Route::post('dashboard/faculty/edit/{id}','Dashboard\FacultyController@edit')->name('edit_faculty');
    Route::get('dashboard/faculty/del/{id}','Dashboard\FacultyController@delete')->name('del_faculty');

    Route::get('dashboard/getDepartment', 'Dashboard\DepartmentController@get_department')->name('get_department');
    Route::get('dashboard/getLevel', 'Dashboard\DepartmentController@get_level')->name('get_level');
    Route::get('dashboard/department','Dashboard\DepartmentController@index')->name('department');
    Route::post('dashboard/department/add','Dashboard\DepartmentController@add')->name('add_department');
    Route::post('dashboard/department/edit/{id}','Dashboard\DepartmentController@edit')->name('edit_department');
    Route::get('dashboard/department/del/{id}','Dashboard\DepartmentController@delete')->name('del_department');
    Route::post('dashboard/department/level/add','Dashboard\DepartmentController@add_level')->name('add_level');
    Route::get('dashboard/department/level/del/{id}','Dashboard\DepartmentController@delete_level')->name('del_level');

    Route::get('dashboard/subject','Dashboard\SubjectController@index')->name('subject');
    Route::post('dashboard/subject/add','Dashboard\SubjectController@add')->name('add_subject');
    Route::post('dashboard/subject/edit/{id}','Dashboard\SubjectController@edit')->name('edit_subject');
    Route::get('dashboard/subject/del/{id}','Dashboard\SubjectController@delete')->name('del_subject');
    Route::get('dashboard/getSubject','Dashboard\SubjectController@get_subject')->name('get_subject');


    Route::get('dashboard/posts/approved','Dashboard\PostController@approved')->name('approved_posts');
    Route::get('dashboard/posts/waiting','Dashboard\PostController@waiting')->name('waiting_posts');
    Route::get('dashboard/posts/rejected','Dashboard\PostController@rejected')->name('rejected_posts');
    Route::get('dashboard/posts/reports','Dashboard\PostController@reports')->name('reports_posts');
    Route::get('dashboard/posts/admin','Dashboard\PostController@admin')->name('admin_posts');
    Route::post('dashboard/posts/add','Dashboard\PostController@add_post')->name('add_post');
    Route::post('dashboard/posts/edit','Dashboard\PostController@edit_post')->name('edit_post');
    Route::get('dashboard/posts/del/{id}','Dashboard\PostController@del_post')->name('del_post');
    Route::get('dashboard/posts/to_approve/{id}','Dashboard\PostController@to_approve')->name('to_approve_post');
    Route::get('dashboard/posts/to_reject/{id}','Dashboard\PostController@to_reject')->name('to_reject_post');

    Route::get('dashboard/posts/comments','Dashboard\PostController@comments')->name('posts_comment');
    Route::post('dashboard/posts/comments/add','Dashboard\PostController@add_comment')->name('add_post_comment');
    Route::post('dashboard/posts/comments/edit','Dashboard\PostController@edit_comment')->name('edit_post_comment');
    Route::get('dashboard/posts/comments/del/{id}','Dashboard\PostController@del_comment')->name('del_post_comment');


    Route::get('dashboard/news/approved','Dashboard\NewsController@approved')->name('approved_news');
    Route::get('dashboard/news/waiting','Dashboard\NewsController@waiting')->name('waiting_news');
    Route::get('dashboard/news/rejected','Dashboard\NewsController@rejected')->name('rejected_news');
    Route::get('dashboard/news/reports','Dashboard\NewsController@reports')->name('reports_news');
    Route::get('dashboard/news/admin','Dashboard\NewsController@admin')->name('admin_news');
    Route::post('dashboard/news/add','Dashboard\NewsController@add_news')->name('add_news');
    Route::post('dashboard/news/edit','Dashboard\NewsController@edit_news')->name('edit_news');
    Route::get('dashboard/news/del/{id}','Dashboard\NewsController@del_news')->name('del_news');
    Route::get('dashboard/news/to_approve/{id}','Dashboard\NewsController@to_approve')->name('to_approve_news');
    Route::get('dashboard/news/to_reject/{id}','Dashboard\NewsController@to_reject')->name('to_reject_news');


    Route::get('dashboard/questions/approved','Dashboard\QuestionController@approved')->name('approved_questions');
    Route::get('dashboard/questions/waiting','Dashboard\QuestionController@waiting')->name('waiting_questions');
    Route::get('dashboard/questions/rejected','Dashboard\QuestionController@rejected')->name('rejected_questions');
    Route::get('dashboard/questions/reports','Dashboard\QuestionController@reports')->name('reports_questions');
    Route::get('dashboard/questions/to_approve/{id}','Dashboard\QuestionController@to_approve')->name('to_approve_question');
    Route::get('dashboard/questions/to_reject/{id}','Dashboard\QuestionController@to_reject')->name('to_reject_question');
    Route::get('dashboard/questions/del/{id}','Dashboard\QuestionController@delete')->name('del_question');

    Route::get('dashboard/questions/comments','Dashboard\QuestionController@comments')->name('questions_comment');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

class Post extends Model implements HasMedia
{
    use HasMediaTrait;

    protected $table = 'posts';
    protected $fillable= ['text' ,'user_id' , 'approved' , 'likes' , 'report' , 'liked_by'];

    public function registerMediaCollections()
    {
        $this->addMediaCollection('post')
            ->singleFile();
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }

    public function getImgAttribute()
    {
        $file = $this->getMedia('post')->last();

        $url = '';
        if ($file) {
            $url = asset('storage/' . $file->id . '/' . $file->file_name);
        }

        return $url;
    }

    public function user()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function comments(){
        return $this->hasMany(Comment::class)->with('user');
    }

}

resources/views/Pages/Posts/approved.blade.php
@extends('layouts.app')
@section('title')
    Approved Posts
@endsection

@section('content')

    <div class="row" style="width: 100%;padding: 10px">
        <h2 class="text-center col-md-10"> <i class="nav-icon fas fa-thumbs-up"> </i> Approved Posts  </h2>
        <input class="col-md-2 form-control input-lg" type="text" id="search" onkeyup="fun_search()" name="search" placeholder="Search ... " autocomplete="off">
    </div>
    <div class="row" style="padding: 10px">
        @if(session('message'))
            <div class="alert alert-default-success alert-dismissible fade show text-center font-weight-bold " role="alert" style="width: 100%">
                {{session('message')}} <i class="fa fa-check-circle"></i>
            </div>
        @endif
        <div class="card table-responsive" style="width: 100%">
            <table class="table table-bordered data-table table-hover" style="vertical-align: middle;text-align: center;">
                <thead class="thead-light">
                <tr>
                    <th width="10%" class="align-middle"><i class="fas fa-bars"></i>  </th>
                    <th width="40%" class="align-middle"><i class="fas fa-newspaper"></i> Text </th>
                    <th width="10%" class="align-middle"><i class="fas fa-thumbs-up"></i> Like </th>
                    <th width="10%" class="align-middle"><i class="fas fa-comment"></i> Comment </th>
                    <th width="15%" class="align-middle"><i class="fas fa-user"></i> User </th>
                    <th width="15%" class="align-middle"><i class="fas fa-tools"></i> Tools </th>
                </tr>
                </thead>
                <tbody>
                @foreach($posts as $key=>$post)
                    <tr id="data">
                        <td class="align-middle">{{$key+1}}</td>
                        <td class="align-middle">{{$post->text}}
                            @if($post->img)
                                <br>
                                <a href="{{asset($post->img)}}" target="_blank">
                                    <img src="{{asset($post->img)}}" width="100px">
                                </a>
                            @endif
                        </td>
                        <td class="align-middle">{{$post->likes}}</td>
                        <td class="align-middle">{{$post->comments->count()}}</td>
                        <td class="align-middle">{{$post->user->user_name}}</td>
                        <td>
                            <a  data-toggle="modal" data-target="#del_post" class="btn btn-danger del_post" data-id="{{$post->id}}"><i class="fas fa-minus-circle"></i>  </a>
                            <a href="{{route('to_reject_post',$post->id)}}" class="btn btn-warning"><i class="fas fa-ban"></i>  </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    </div>

    {{-- Start Delete Modal--}}
    <div class="modal fade" id="del_post" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document" >
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h5 class="modal-title w-100 font-weight-bold"> Delete Post </h5>
                    <button type="button" style="float: left" class="close" data-dismiss="modal" aria-label="Close">
                        <span  aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    Are You Sure Delete ?
                </div>
                <div class="modal-footer">
                    <form id="form_del_post" role="form" method="GET" action="">
                        <button class="btn btn-danger"><i class="fas fa-minus-circle"></i> Delete </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- End Delete Modal --}}

@endsection
<script src="{{asset('dist/js/jquery.min.js')}}"></script>
<script src="{{asset('dist/js/bootstrap.min.js')}}"></script>
<script>
    $(document).on('click','.del_post',function () {
        var id=$(this).data('id');
        var action="{{route('del_post',"id")}}";
        action=action.replace('id',id);
        $('#form_del_post').attr('action',action);
        $('#del_post').modal('show');
    });
    $(document).ready(function(){
        $("#search").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $(".table #data").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

resources/views/Pages/Posts/comments.blade.php
@extends('layouts.app')
@section('title')
    Post Comments
@endsection

@section('content')

    <div class="row" style="width: 100%;padding: 10px">
        <h2 class="text-center col-md-12"> <i class="nav-icon fas fa-comments"> </i> Post Comments  </h2>
    </div>
    <div class="row" style="padding: 10px">
        @if(session('message'))
            <div class="alert alert-default-success alert-dismissible fade show text-center font-weight-bold " role="alert" style="width: 100%">
                {{session('message')}} <i class="fa fa-check-circle"></i>
            </div>
        @endif
            <div class="card table-responsive" style="width: 100%">
                <table class="table table-bordered data-table table-hover" style="vertical-align: middle;text-align: center;">
                    <thead class="thead-light">
                    <tr>
                        <th width="5%" class="align-middle"><i class="fas fa-bars"></i>  </th>
                        <th width="50%" class="align-middle"><i class="fas fa-file-alt"></i> Post </th>
                        <th width="15%" class="align-middle"><i class="fas fa-user"></i> User </th>
                        <th width="10%" class="align-middle"><i class="fas fa-thumbs-up"></i>  Likes </th>
                        <th width="10%" class="align-middle"><i class="fas fa-comments"></i>  Comments </th>
                        <th width="10%" class="align-middle"><i class="fas fa-ban"></i>  Report </th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($posts as $post)
                        <tr id="data">
                            <td class="align-middle accordion-toggle collapsed " data-toggle="collapse"  href="#id{{$post->id}}"> <i class="fas fa-bars"></i></td>
                            <td class="align-middle">{{$post->text}}
                                @if($post->img)
                                    <br>
                                    <a href="{{asset($post->img)}}" target="_blank">
                                        <img src="{{asset($post->img)}}" width="100px">
                                    </a>
                                @endif
                            </td>
                            <td class="align-middle">{{$post->user->user_name}}</td>
                            <td class="align-middle">{{$post->likes}}</td>
                            <td class="align-middle">{{$post->comments->count()}}</td>
                            <td class="align-middle">{{$post->report}}</td>
                        </tr>
                        <tr class="hide-table-padding">
                            <td id="id{{$post->id}}" class="collapse in py-2">
                                <a class="btn btn-success add_post_comment mt-2" data-toggle="modal" data-target="#add_post_comment" data-id="{{$post->id}}"><i class="nav-icon fas fa-plus-circle"></i>  </a>
                            </td>
                            <td colspan="5">
                                <div id="id{{$post->id}}" class="collapse in py-2" style="width: 100%">
                                    @foreach($post->comments as $comment)
                                        <div class="row py-1">
                                            <div class="col-4"><i class="fas fa-comment"></i> {{$comment->text}}  </div>
                                            <div class="col-2"><i class="fas fa-thumbs-up"></i> {{$comment->likes}}  </div>
                                            <div class="col-2"><i class="fas fa-ban"></i> {{$comment->report}}  </div>
                                            <div class="col-2"><i class="fas fa-user"></i> {{$comment->user->user_name}}  </div>
                                            <div class="col-2">
                                                <a  class="btn btn-primary edit_post_comment" data-target="#edit_post_comment" data-id="{{$comment->id}}"  data-text="{{$comment->text}}" data-toggle="modal" ><i class="nav-icon fas fa-edit"></i>  </a>
                                                <a  data-toggle="modal" data-target="#del_post_comment" class="btn btn-danger del_post_comment" data-id="{{$comment->id}}"><i class="fas fa-minus-circle"></i>  </a>
                                            </div>
                                        </div>
                                        <hr>
                                    @endforeach
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

    </div>
    {{--Start Add Modal--}}
    <div class="modal fade" id="add_post_comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
        <div class="modal-dialog" role="document" >
            <form role="form" method="POST" action="{{route('add_post_comment')}}" autocomplete="off">
                @csrf
                <div class="modal-content">
                    <div class="modal-header text-center">
                        <h4 class="modal-title w-100 font-weight-bold">Add Comment </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body mx-3">
                        <div class="md-form mb-2" >
                            <input type="hidden" name="post_id" id="post_id">
                            <label data-error="wrong" data-success="right" ><i class="fas fa-comment-alt prefix grey-text"></i> Comment </label>
                            <textarea name='text' class="form-control validate text-center" required></textarea>
                        </div>
                    </div>

                    <div class="modal-footer d-flex justify-content-center">
                        <button class="btn btn-success"> Add <i class="fas fa-plus ml-1"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {{--End Add Modal--}}
    {{-- Start Delete Modal--}}
    <div class="modal fade" id="del_comment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document" >
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h5 class="modal-title w-100 font-weight-bold"> Delete Comment </h5>
                    <button type="button" style="float: left" class="close" data-dismiss="modal" aria-label="Close">
                        <span  aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    Are You Sure Delete ?
                </div>
                <div class="modal-footer">
                    <form id="form_del_comment" role="form" method="GET" action="">
                        <button class="btn btn-danger"><i class="fas fa-minus-circle"></i> Delete </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- End Delete Modal --}}
    {{--Start Edit Modal--}}
    <div class="modal fade" id="edit_post_comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
        <div class="modal-dialog" role="document" >
            <form id="form_edit_post_comment" role="form" method="POST" action="{{route('edit_post_comment')}}" autocomplete="off">
                @csrf
                <div class="modal-content">
                    <div class="modal-header text-center">
                        <h4 class="modal-title w-100 font-weight-bold">Edit Comment </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body mx-3">
                        <input type="hidden" id="id_comment" name="id">
                        <div class="md-form mb-2" >
                            <label data-error="wrong" data-success="right" ><i class="fas fa-file-alt prefix grey-text"></i> Post </label>
                            <textarea name='text' id="text_comment" class="form-control validate text-center" required></textarea>
                        </div>
                    </div>

                    <div class="modal-footer d-flex justify-content-center">
                        <button class="btn btn-success"> Edit <i class="fas fa-edit ml-1"></i></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {{--End Edit Modal--}}

@endsection
<script src="{{asset('dist/js/jquery.min.js')}}"></script>
<script src="{{asset('dist/js/bootstrap.min.js')}}"></script>
<script>
    $(document).on('click', '.add_post_comment', function() {
        $('#post_id').val($(this).data('id'));
        $('#add_post_comment').modal('show');
    });
    $(document).on('click', '.edit_post_comment', function() {
        $('#id_comment').val($(this).data('id'));
        $('#text_comment').val($(this).data('text'));
        $('#edit_post_comment').modal('show');
    });
    $(document).on('click','.del_post_comment',function () {
        var id=$(this).data('id');
        var action="{{route('del_post_comment',"id")}}";
        action=action.replace('id',id);
        $('#form_del_comment').attr('action',action);
        $('#del_comment').modal('show');
    });

</script>

resources/views/Pages/Posts/reject.blade.php
@extends('layouts.app')
@section('title')
    Refused Posts
@endsection

@section('content')

    <div class="row" style="width: 100%;padding: 10px">
        <h2 class="text-center col-md-12"> <i class="nav-icon fas fa-ban"> </i> Refused Posts  </h2>
    </div>
    <div class="row" style="padding: 10px">
        @if(session('message'))
            <div class="alert alert-default-success alert-dismissible fade show text-center font-weight-bold " role="alert" style="width: 100%">
                {{session('message')}} <i class="fa fa-check-circle"></i>
            </div>
        @endif
        <div class="card table-responsive" style="width: 100%">
            <table class="table table-bordered data-table table-hover" style="vertical-align: middle;text-align: center;">
                <thead class="thead-light">
                <tr>
                    <th width="10%" class="align-middle"><i class="fas fa-bars"></i>  </th>
                    <th width="40%" class="align-middle"><i class="fas fa-newspaper"></i> Text </th>
                    <th width="10%" class="align-middle"><i class="fas fa-thumbs-up"></i> Like </th>
                    <th width="15%" class="align-middle"><i class="fas fa-user"></i> User </th>
                    <th width="10%" class="align-middle"><i class="fas fa-ban"></i> Report </th>
                    <th width="15%" class="align-middle"><i class="fas fa-tools"></i> Tools </th>
                </tr>
                </thead>
                <tbody>
                @foreach($posts as $key=>$post)
                    <tr id="data">
                        <td class="align-middle">{{$key+1}}</td>
                        <td class="align-middle">{{$post->text}}
                            @if($post->img)
                                <br>
                                <a href="{{asset($post->img)}}" target="_blank">
                                    <img src="{{asset($post->img)}}" width="100px">
                                </a>
                            @endif
                        </td>
                        <td class="align-middle">{{$post->likes}}</td>
                        <td class="align-middle">{{$post->user->user_name}}</td>
                        <td class="align-middle">{{$post->report}}</td>
                        <td>
                            <a  data-toggle="modal" data-target="#del_post" class="btn btn-danger del_post" data-id="{{$post->id}}"><i class="fas fa-minus-circle"></i>  </a>
                            <a href="{{route('to_approve_post',$post->id)}}" class="btn btn-info m-2"><i class="fas fa-check-circle"></i>  </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    </div>

    {{-- Start Delete Modal--}}
    <div class="modal fade" id="del_post" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document" >
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h5 class="modal-title w-100 font-weight-bold"> Delete Post </h5>
                    <button type="button" style="float: left" class="close" data-dismiss="modal" aria-label="Close">
                        <span  aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body text-center">
                    Are You Sure Delete ?
                </div>
                <div class="modal-footer">
                    <form id="form_del_post" role="form" method="GET" action="">
                        <button class="btn btn-danger"><i class="fas fa-minus-circle"></i> Delete </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- End Delete Modal --}}

@endsection
<script src="{{asset('dist/js/jquery.min.js')}}"></script>
<script src="{{asset('dist/js/bootstrap.min.js')}}"></script>
<script>
    $(document).on('click','.del_post',function () {
        var id=$(this).data('id');
        var action="{{route('del_post',"id")}}";
        action=action.replace('id',id);
        $('#form_del_post').attr('action',action);
        $('#del_post').modal('show');
    });
</script>